$ErrorActionPreference = 'Stop'

function Ensure-File([string]$Path, [string]$Content = "") {
	$dir = Split-Path -Parent $Path
	if ($dir -and -not (Test-Path -LiteralPath $dir)) {
		New-Item -ItemType Directory -Path $dir -Force | Out-Null
	}
	if (-not (Test-Path -LiteralPath $Path)) {
		if ($null -eq $Content) { $Content = "" }
		Set-Content -LiteralPath $Path -Value $Content -NoNewline -Encoding UTF8
	}
}

$root = Split-Path -Parent $PSScriptRoot

# Create all files (parent directories will be created automatically).
$files = @(
	# top-level
	'README.md',
	'.gitignore',
	'.env',
	'.env.example',
	'docker-compose.yml',
	'Makefile',
	'LICENSE',

	# backend
	'backend/Dockerfile',
	'backend/requirements.txt',
	'backend/main.py',
	'backend/config.py',
	'backend/auth/__init__.py',
	'backend/auth/jwt_handler.py',
	'backend/auth/password_handler.py',
	'backend/auth/dependencies.py',
	'backend/auth/rbac.py',
	'backend/routers/__init__.py',
	'backend/routers/auth_router.py',
	'backend/routers/order_router.py',
	'backend/routers/menu_router.py',
	'backend/routers/kitchen_router.py',
	'backend/routers/runner_router.py',
	'backend/routers/admin_router.py',
	'backend/routers/notification_router.py',
	'backend/routers/trivia_router.py',
	'backend/routers/health_router.py',
	'backend/models/__init__.py',
	'backend/models/user_model.py',
	'backend/models/station_model.py',
	'backend/models/menu_item_model.py',
	'backend/models/order_model.py',
	'backend/models/order_item_model.py',
	'backend/models/runner_model.py',
	'backend/models/order_status_history_model.py',
	'backend/models/feedback_model.py',
	'backend/models/notification_model.py',
	'backend/models/trivia_question_model.py',
	'backend/models/trivia_score_model.py',
	'backend/models/ai_training_data_model.py',
	'backend/models/system_log_model.py',
	'backend/schemas/__init__.py',
	'backend/schemas/auth_schema.py',
	'backend/schemas/user_schema.py',
	'backend/schemas/order_schema.py',
	'backend/schemas/menu_schema.py',
	'backend/schemas/kitchen_schema.py',
	'backend/schemas/runner_schema.py',
	'backend/schemas/feedback_schema.py',
	'backend/schemas/notification_schema.py',
	'backend/schemas/trivia_schema.py',
	'backend/schemas/error_schema.py',
	'backend/services/__init__.py',
	'backend/services/order_service.py',
	'backend/services/menu_service.py',
	'backend/services/kitchen_service.py',
	'backend/services/runner_service.py',
	'backend/services/runner_assignment_service.py',
	'backend/services/notification_service.py',
	'backend/services/trivia_service.py',
	'backend/services/feedback_service.py',
	'backend/services/eta_service.py',
	'backend/services/analytics_service.py',
	'backend/services/admin_service.py',
	'backend/database/__init__.py',
	'backend/database/connection.py',
	'backend/database/session.py',
	'backend/database/seed_data.py',
	'backend/migrations/env.py',
	'backend/migrations/alembic.ini',
	'backend/migrations/versions/001_create_users_table.py',
	'backend/migrations/versions/002_create_stations_table.py',
	'backend/migrations/versions/003_create_menu_items_table.py',
	'backend/migrations/versions/004_create_orders_table.py',
	'backend/migrations/versions/005_create_order_items_table.py',
	'backend/migrations/versions/006_create_runners_table.py',
	'backend/migrations/versions/007_create_order_status_history_table.py',
	'backend/migrations/versions/008_create_feedback_table.py',
	'backend/migrations/versions/009_create_notifications_table.py',
	'backend/migrations/versions/010_create_trivia_questions_table.py',
	'backend/migrations/versions/011_create_trivia_scores_table.py',
	'backend/migrations/versions/012_create_ai_training_data_table.py',
	'backend/migrations/versions/013_create_system_logs_table.py',
	'backend/websocket/__init__.py',
	'backend/websocket/socket_manager.py',
	'backend/websocket/events.py',
	'backend/websocket/rooms.py',
	'backend/middleware/__init__.py',
	'backend/middleware/rate_limiter.py',
	'backend/middleware/cors_middleware.py',
	'backend/middleware/logging_middleware.py',
	'backend/middleware/error_handler.py',
	'backend/utils/__init__.py',
	'backend/utils/id_generator.py',
	'backend/utils/validators.py',
	'backend/utils/constants.py',
	'backend/utils/helpers.py',
	'backend/utils/time_utils.py',
	'backend/logs/app.log',
	'backend/logs/error.log',

	# frontend
	'frontend/Dockerfile',
	'frontend/package.json',
	'frontend/package-lock.json',
	'frontend/.eslintrc.js',
	'frontend/.prettierrc',
	'frontend/tailwind.config.js',
	'frontend/postcss.config.js',
	'frontend/vite.config.js',
	'frontend/public/index.html',
	'frontend/public/favicon.ico',
	'frontend/public/manifest.json',
	'frontend/public/images/logo.png',
	'frontend/public/images/placeholder-food.png',
	'frontend/public/images/qr-sample.png',
	'frontend/src/main.jsx',
	'frontend/src/App.jsx',
	'frontend/src/index.css',
	'frontend/src/api/axiosInstance.js',
	'frontend/src/api/authApi.js',
	'frontend/src/api/orderApi.js',
	'frontend/src/api/menuApi.js',
	'frontend/src/api/kitchenApi.js',
	'frontend/src/api/runnerApi.js',
	'frontend/src/api/adminApi.js',
	'frontend/src/api/notificationApi.js',
	'frontend/src/api/triviaApi.js',
	'frontend/src/context/AuthContext.jsx',
	'frontend/src/context/CartContext.jsx',
	'frontend/src/context/OrderContext.jsx',
	'frontend/src/context/SocketContext.jsx',
	'frontend/src/context/NotificationContext.jsx',
	'frontend/src/hooks/useAuth.js',
	'frontend/src/hooks/useCart.js',
	'frontend/src/hooks/useOrder.js',
	'frontend/src/hooks/useSocket.js',
	'frontend/src/hooks/useNotification.js',
	'frontend/src/hooks/useTrivia.js',
	'frontend/src/pages/auth/LoginPage.jsx',
	'frontend/src/pages/auth/ForgotPasswordPage.jsx',
	'frontend/src/pages/engineer/MenuPage.jsx',
	'frontend/src/pages/engineer/CartPage.jsx',
	'frontend/src/pages/engineer/OrderConfirmationPage.jsx',
	'frontend/src/pages/engineer/OrderTrackingPage.jsx',
	'frontend/src/pages/engineer/OrderHistoryPage.jsx',
	'frontend/src/pages/engineer/FeedbackPage.jsx',
	'frontend/src/pages/engineer/ProfilePage.jsx',
	'frontend/src/pages/kitchen/KitchenDashboardPage.jsx',
	'frontend/src/pages/kitchen/IncomingOrdersPage.jsx',
	'frontend/src/pages/kitchen/PreparingOrdersPage.jsx',
	'frontend/src/pages/kitchen/ReadyOrdersPage.jsx',
	'frontend/src/pages/kitchen/MenuAvailabilityPage.jsx',
	'frontend/src/pages/runner/RunnerDashboardPage.jsx',
	'frontend/src/pages/runner/ActiveDeliveriesPage.jsx',
	'frontend/src/pages/runner/DeliveryDetailPage.jsx',
	'frontend/src/pages/runner/RunnerHistoryPage.jsx',
	'frontend/src/pages/admin/AdminDashboardPage.jsx',
	'frontend/src/pages/admin/MenuManagementPage.jsx',
	'frontend/src/pages/admin/UserManagementPage.jsx',
	'frontend/src/pages/admin/ReportsPage.jsx',
	'frontend/src/pages/admin/AIModelMonitorPage.jsx',
	'frontend/src/pages/admin/SystemSettingsPage.jsx',
	'frontend/src/pages/admin/TriviaManagementPage.jsx',
	'frontend/src/pages/trivia/TriviaGamePage.jsx',
	'frontend/src/pages/trivia/LeaderboardPage.jsx',
	'frontend/src/pages/common/NotFoundPage.jsx',
	'frontend/src/pages/common/ServerErrorPage.jsx',
	'frontend/src/pages/common/OfflinePage.jsx',
	'frontend/src/components/common/Navbar.jsx',
	'frontend/src/components/common/Footer.jsx',
	'frontend/src/components/common/Sidebar.jsx',
	'frontend/src/components/common/LoadingSpinner.jsx',
	'frontend/src/components/common/SkeletonLoader.jsx',
	'frontend/src/components/common/Toast.jsx',
	'frontend/src/components/common/Modal.jsx',
	'frontend/src/components/common/Button.jsx',
	'frontend/src/components/common/Badge.jsx',
	'frontend/src/components/common/Card.jsx',
	'frontend/src/components/common/SearchBar.jsx',
	'frontend/src/components/common/Pagination.jsx',
	'frontend/src/components/common/EmptyState.jsx',
	'frontend/src/components/common/ErrorBoundary.jsx',
	'frontend/src/components/common/OfflineBanner.jsx',
	'frontend/src/components/common/ConnectionIndicator.jsx',
	'frontend/src/components/common/ProtectedRoute.jsx',
	'frontend/src/components/auth/LoginForm.jsx',
	'frontend/src/components/auth/SessionExpiredModal.jsx',
	'frontend/src/components/menu/MenuItemCard.jsx',
	'frontend/src/components/menu/MenuCategoryFilter.jsx',
	'frontend/src/components/menu/MenuItemDetail.jsx',
	'frontend/src/components/menu/QuantitySelector.jsx',
	'frontend/src/components/menu/UnavailableBadge.jsx',
	'frontend/src/components/cart/CartItem.jsx',
	'frontend/src/components/cart/CartSummary.jsx',
	'frontend/src/components/cart/CartIcon.jsx',
	'frontend/src/components/cart/PriorityToggle.jsx',
	'frontend/src/components/cart/SpecialInstructions.jsx',
	'frontend/src/components/cart/ETAPreview.jsx',
	'frontend/src/components/order/OrderCard.jsx',
	'frontend/src/components/order/OrderStatusBadge.jsx',
	'frontend/src/components/order/ProgressBar.jsx',
	'frontend/src/components/order/ETADisplay.jsx',
	'frontend/src/components/order/RunnerInfo.jsx',
	'frontend/src/components/order/OrderTimeline.jsx',
	'frontend/src/components/order/CancelOrderButton.jsx',
	'frontend/src/components/feedback/StarRating.jsx',
	'frontend/src/components/feedback/FeedbackForm.jsx',
	'frontend/src/components/kitchen/KitchenOrderCard.jsx',
	'frontend/src/components/kitchen/OrderTimer.jsx',
	'frontend/src/components/kitchen/StatusUpdateButton.jsx',
	'frontend/src/components/kitchen/MenuToggle.jsx',
	'frontend/src/components/kitchen/KitchenStats.jsx',
	'frontend/src/components/runner/DeliveryCard.jsx',
	'frontend/src/components/runner/RunnerStatusToggle.jsx',
	'frontend/src/components/runner/DeliveryActions.jsx',
	'frontend/src/components/runner/ReportIssueButton.jsx',
	'frontend/src/components/runner/RunnerStats.jsx',
	'frontend/src/components/admin/StatCard.jsx',
	'frontend/src/components/admin/OrderChart.jsx',
	'frontend/src/components/admin/PopularItemsChart.jsx',
	'frontend/src/components/admin/PeakHoursChart.jsx',
	'frontend/src/components/admin/RunnerPerformanceTable.jsx',
	'frontend/src/components/admin/AIAccuracyChart.jsx',
	'frontend/src/components/admin/MenuItemForm.jsx',
	'frontend/src/components/admin/UserForm.jsx',
	'frontend/src/components/admin/UserTable.jsx',
	'frontend/src/components/admin/TriviaQuestionForm.jsx',
	'frontend/src/components/trivia/TriviaQuestion.jsx',
	'frontend/src/components/trivia/TriviaTimer.jsx',
	'frontend/src/components/trivia/TriviaScore.jsx',
	'frontend/src/components/trivia/TriviaPopup.jsx',
	'frontend/src/components/trivia/LeaderboardTable.jsx',
	'frontend/src/components/notification/NotificationBell.jsx',
	'frontend/src/components/notification/NotificationDropdown.jsx',
	'frontend/src/components/notification/NotificationItem.jsx',
	'frontend/src/components/notification/SoundAlert.jsx',
	'frontend/src/routes/AppRoutes.jsx',
	'frontend/src/routes/EngineerRoutes.jsx',
	'frontend/src/routes/KitchenRoutes.jsx',
	'frontend/src/routes/RunnerRoutes.jsx',
	'frontend/src/routes/AdminRoutes.jsx',
	'frontend/src/utils/formatters.js',
	'frontend/src/utils/validators.js',
	'frontend/src/utils/constants.js',
	'frontend/src/utils/helpers.js',
	'frontend/src/utils/soundManager.js',
	'frontend/src/services/socketService.js',
	'frontend/src/services/storageService.js',
	'frontend/src/services/cacheService.js',
	'frontend/src/services/pushNotificationService.js',
	'frontend/src/assets/images/logo.svg',
	'frontend/src/assets/images/empty-cart.svg',
	'frontend/src/assets/images/order-success.svg',
	'frontend/src/assets/images/no-orders.svg',
	'frontend/src/assets/images/offline.svg',
	'frontend/src/assets/images/error.svg',
	'frontend/src/assets/sounds/new-order.mp3',
	'frontend/src/assets/sounds/order-ready.mp3',
	'frontend/src/assets/sounds/notification.mp3',
	'frontend/src/assets/sounds/urgent-alert.mp3',
	'frontend/src/assets/fonts/Inter-Regular.woff2',
	'frontend/src/assets/fonts/Inter-Medium.woff2',
	'frontend/src/assets/fonts/Inter-Bold.woff2',

	# ai_module
	'ai_module/__init__.py',
	'ai_module/requirements.txt',
	'ai_module/data/training_data.csv',
	'ai_module/data/test_data.csv',
	'ai_module/data/.gitkeep',
	'ai_module/models/eta_model.pkl',
	'ai_module/models/eta_model_backup.pkl',
	'ai_module/models/model_metadata.json',
	'ai_module/models/.gitkeep',
	'ai_module/scripts/generate_data.py',
	'ai_module/scripts/train_model.py',
	'ai_module/scripts/evaluate_model.py',
	'ai_module/scripts/retrain.py',
	'ai_module/scripts/export_training_data.py',
	'ai_module/core/__init__.py',
	'ai_module/core/predictor.py',
	'ai_module/core/feature_engineering.py',
	'ai_module/core/fallback.py',
	'ai_module/core/model_loader.py',
	'ai_module/notebooks/data_exploration.ipynb',
	'ai_module/notebooks/model_comparison.ipynb',
	'ai_module/notebooks/feature_importance.ipynb',

	# automation
	'automation/__init__.py',
	'automation/requirements.txt',
	'automation/load_testing/load_simulator.py',
	'automation/load_testing/locustfile.py',
	'automation/load_testing/config.py',
	'automation/load_testing/report_generator.py',
	'automation/data_generation/seed_engineers.py',
	'automation/data_generation/seed_menu.py',
	'automation/data_generation/seed_stations.py',
	'automation/data_generation/seed_runners.py',
	'automation/data_generation/seed_trivia.py',
	'automation/data_generation/seed_all.py',
	'automation/simulation/order_flow_simulator.py',
	'automation/simulation/kitchen_simulator.py',
	'automation/simulation/runner_simulator.py',
	'automation/simulation/traffic_pattern_simulator.py',
	'automation/reports/load_test_report.txt',
	'automation/reports/.gitkeep',

	# tests
	'tests/__init__.py',
	'tests/conftest.py',
	'tests/pytest.ini',
	'tests/unit/backend/__init__.py',
	'tests/unit/backend/test_auth.py',
	'tests/unit/backend/test_order_service.py',
	'tests/unit/backend/test_runner_assignment.py',
	'tests/unit/backend/test_menu_service.py',
	'tests/unit/backend/test_kitchen_service.py',
	'tests/unit/backend/test_notification_service.py',
	'tests/unit/backend/test_trivia_service.py',
	'tests/unit/backend/test_validators.py',
	'tests/unit/backend/test_id_generator.py',
	'tests/unit/backend/test_time_utils.py',
	'tests/unit/frontend/CartSummary.test.jsx',
	'tests/unit/frontend/ProgressBar.test.jsx',
	'tests/unit/frontend/MenuItemCard.test.jsx',
	'tests/unit/frontend/StarRating.test.jsx',
	'tests/unit/frontend/PriorityToggle.test.jsx',
	'tests/unit/frontend/OrderStatusBadge.test.jsx',
	'tests/unit/frontend/formatters.test.js',
	'tests/unit/frontend/validators.test.js',
	'tests/unit/ai/__init__.py',
	'tests/unit/ai/test_predictor.py',
	'tests/unit/ai/test_feature_engineering.py',
	'tests/unit/ai/test_fallback.py',
	'tests/unit/ai/test_model_accuracy.py',
	'tests/integration/__init__.py',
	'tests/integration/test_order_lifecycle.py',
	'tests/integration/test_auth_flow.py',
	'tests/integration/test_kitchen_flow.py',
	'tests/integration/test_runner_flow.py',
	'tests/integration/test_websocket_events.py',
	'tests/integration/test_ai_integration.py',
	'tests/integration/test_concurrent_orders.py',
	'tests/integration/test_database_consistency.py',
	'tests/e2e/cypress.config.js',
	'tests/e2e/fixtures/engineer.json',
	'tests/e2e/fixtures/menu.json',
	'tests/e2e/fixtures/order.json',
	'tests/e2e/support/commands.js',
	'tests/e2e/support/e2e.js',
	'tests/e2e/specs/login.cy.js',
	'tests/e2e/specs/place_order.cy.js',
	'tests/e2e/specs/track_order.cy.js',
	'tests/e2e/specs/cancel_order.cy.js',
	'tests/e2e/specs/kitchen_dashboard.cy.js',
	'tests/e2e/specs/runner_delivery.cy.js',
	'tests/e2e/specs/admin_panel.cy.js',
	'tests/e2e/specs/feedback.cy.js',
	'tests/e2e/specs/trivia_game.cy.js',
	'tests/e2e/specs/error_handling.cy.js',
	'tests/e2e/specs/offline_mode.cy.js',

	# docs
	'docs/proposal.pdf',
	'docs/proposal.tex',
	'docs/api_documentation.md',
	'docs/database_schema.md',
	'docs/architecture_diagram.png',
	'docs/setup_guide.md',
	'docs/deployment_guide.md',
	'docs/ai_model_guide.md',
	'docs/testing_guide.md',
	'docs/websocket_events.md',
	'docs/error_codes.md',

	# scripts
	'scripts/setup.sh',
	'scripts/start_dev.sh',
	'scripts/stop_dev.sh',
	'scripts/run_tests.sh',
	'scripts/generate_seed_data.sh',
	'scripts/train_ai_model.sh',
	'scripts/run_load_test.sh',
	'scripts/backup_db.sh',

	# github workflows
	'.github/workflows/ci.yml',
	'.github/workflows/cd.yml',
	'.github/workflows/ai_retrain.yml'
)

foreach ($rel in $files) {
	$path = Join-Path $root ($rel -replace '/', [IO.Path]::DirectorySeparatorChar)
	Ensure-File $path ""
}

# Minimal notebook JSON to satisfy tooling (write only if newly created; above wrote empty, so overwrite with content).
$nbJson = @'
{
	"cells": [
		{
			"cell_type": "markdown",
			"metadata": { "language": "markdown" },
			"source": ["# Notebook"]
		}
	],
	"metadata": {},
	"nbformat": 4,
	"nbformat_minor": 5
}
'@

Set-Content -LiteralPath (Join-Path $root 'ai_module\notebooks\data_exploration.ipynb') -Value $nbJson -NoNewline -Encoding UTF8
Set-Content -LiteralPath (Join-Path $root 'ai_module\notebooks\model_comparison.ipynb') -Value $nbJson -NoNewline -Encoding UTF8
Set-Content -LiteralPath (Join-Path $root 'ai_module\notebooks\feature_importance.ipynb') -Value $nbJson -NoNewline -Encoding UTF8

Write-Host "Scaffold complete at: $root" -ForegroundColor Green
